from _typeshed import Incomplete

def disable_traceback_filtering() -> None: ...
def enable_traceback_filtering() -> None: ...
def is_traceback_filtering_enabled() -> bool: ...
def __getattr__(name: str) -> Incomplete: ...
