class Captured:
    stdout: str
    stderr: str
    log: str
    name: str | None
    failed: bool

    def __init__(
        self,
        stdout: str | None = None,
        stderr: str | None = None,
        log: str | None = None,
        name: str | None = None,
        failed: bool = False,
    ) -> None: ...
    def reset(self) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def output(self) -> str: ...
    def has_output(self) -> bool: ...
    def make_output(self, separator: str | None = None) -> str: ...
    def make_report(self, template: str | None = None) -> str: ...
    def __bool__(self) -> bool: ...

class ManyCaptured:
    captures: list[Captured]

    def __init__(self, captures: list[Captured] | None = None) -> None: ...
    def add_captured(self, other: Captured | ManyCaptured, use_merge: bool = True) -> None: ...
    def has_failed(self) -> bool: ...
    @property
    def failed(self) -> bool: ...
    @property
    def status(self) -> str: ...
    @property
    def stdout(self) -> str: ...
    @property
    def stderr(self) -> str: ...
    @property
    def log(self) -> str: ...
    @property
    def output(self) -> str: ...
    def reset(self) -> None: ...
    def has_output(self) -> bool: ...
    def make_output(self, separator: str | None = None) -> str: ...
    def make_report(self, template: str | None = None, separator: str | None = None) -> str: ...
    def __bool__(self) -> bool: ...
