from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any, TypeVar

from behave.model import Feature, Row, Scenario, Table
from behave.capture import Captured
from behave.configuration import Configuration

_T = TypeVar("_T")

class Context:
    LAYER_NAMES: list[str]
    FAIL_ON_CLEANUP_ERRORS: bool

    # Behave-set attributes (may not be present in all scopes)
    feature: Feature | None
    scenario: Scenario | None
    tags: set[str]
    aborted: bool
    failed: bool
    table: Table | None
    text: str | None
    config: Configuration
    active_outline: Row | None
    fail_on_cleanup_errors: bool

    def __init__(self, runner: ModelRunner) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def __contains__(self, name: str) -> bool: ...
    def abort(self, reason: str | None = None) -> None: ...
    def use_or_assign_param(self, name: str, value: _T) -> _T: ...
    def use_or_create_param(self, name: str, factory_func: Callable[..., _T], *args: Any, **kwargs: Any) -> _T: ...
    def use_with_user_mode(self) -> AbstractContextManager[None]: ...
    def execute_steps(self, steps_text: str) -> bool: ...
    def add_cleanup(self, cleanup_func: Callable[..., object], *args: Any, **kwargs: Any) -> None: ...
    @property
    def captured(self) -> Captured: ...
    def attach(self, mime_type: str, data: bytes) -> None: ...

class ModelRunner:
    config: Configuration
    features: list[Feature]
    hooks: dict[str, Callable[..., Any]]
    formatters: list[Any]
    step_registry: Any
    context: Context | None
    feature: Feature | None
    hook_failures: int

    def __init__(
        self, config: Configuration, features: list[Feature] | None = None, step_registry: Any | None = None
    ) -> None: ...
    @property
    def undefined_steps(self) -> list[Any]: ...
    @property
    def aborted(self) -> bool: ...
    @aborted.setter
    def aborted(self, value: bool) -> None: ...
    def abort(self, reason: str | None = None) -> None: ...
    @property
    def captured(self) -> Captured: ...
    def run_model(self, features: list[Feature] | None = None) -> bool: ...
    def run(self) -> bool: ...

class Runner(ModelRunner):
    DEFAULT_DIRECTORY: str
    base_dir: str | None

    def __init__(self, config: Configuration) -> None: ...
    def setup_paths(self) -> None: ...
    def load_hooks(self, filename: str | None = None) -> None: ...
    def load_step_definitions(self, extra_step_paths: list[str] | None = None) -> None: ...
    def run_with_paths(self) -> bool: ...

def use_context_with_mode(context: Context, mode: ContextMode) -> AbstractContextManager[None]: ...
def scoped_context_layer(context: Context, layer: str | None = None) -> AbstractContextManager[Context]: ...

class ContextMode:
    BEHAVE: ContextMode
    USER: ContextMode

class ContextMaskWarning(UserWarning): ...
