from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any

class Context:
    LAYER_NAMES: list[str]
    FAIL_ON_CLEANUP_ERRORS: bool

    # Behave-set attributes (may not be present in all scopes)
    feature: Any  # Feature or None
    scenario: Any  # Scenario or None
    tags: set[str]
    aborted: bool
    failed: bool
    table: Any  # Table or None
    text: str | None
    config: Any  # Configuration
    active_outline: Any  # Row or None
    fail_on_cleanup_errors: bool

    def __init__(self, runner: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def __contains__(self, name: str) -> bool: ...
    def abort(self, reason: str | None = None) -> None: ...
    def use_or_assign_param(self, name: str, value: Any) -> Any: ...
    def use_or_create_param(self, name: str, factory_func: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...
    def use_with_user_mode(self) -> AbstractContextManager[None]: ...
    def execute_steps(self, steps_text: str) -> bool: ...
    def add_cleanup(self, cleanup_func: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
    @property
    def captured(self) -> Any: ...  # Captured
    def attach(self, mime_type: str, data: bytes) -> None: ...
