from typing import Any

class UserData(dict[str, Any]):
    def __init__(self, data: dict[str, Any] | None = None, **kwargs: Any) -> None: ...
    def getint(self, key: str, default: int = 0) -> int: ...
    def getfloat(self, key: str, default: float = 0.0) -> float: ...
    def getbool(self, key: str, default: bool = False) -> bool: ...
    def getas(self, convert: type[Any], key: str, default: Any = None) -> Any: ...

def parse_user_define(text: str) -> tuple[str, str]: ...
