from typing import IO, Any

class StreamOpener:
    name: str | None
    stream: IO[str] | None
    encoding: str

    def __init__(
        self,
        filename: str | None = None,
        stream: IO[str] | None = None,
        encoding: str = "utf-8",
    ) -> None: ...
    def open(self) -> IO[str]: ...
    def close(self) -> None: ...
    def __enter__(self) -> IO[str]: ...
    def __exit__(self, *args: Any) -> None: ...

class Formatter:
    stream_opener: StreamOpener
    stream: IO[str]

    def __init__(self, stream_opener: StreamOpener, config: Any) -> None: ...
    def uri(self, uri: str) -> None: ...
    def feature(self, feature: Any) -> None: ...
    def background(self, background: Any) -> None: ...
    def scenario(self, scenario: Any) -> None: ...
    def step(self, step: Any) -> None: ...
    def match(self, match: Any) -> None: ...
    def result(self, step: Any) -> None: ...
    def eof(self) -> None: ...
    def close(self) -> None: ...
